name: Build and Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Linting
        uses: WhyNotHugo/python-linting@v1.0.0
    
      - name: Run git pull and restart supervisor program on prod server
        uses: JimCronqvist/action-ssh@0.1.1
        with:
          hosts: '${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}}:${{secrets.SSH_PORT}}'
          privateKey: ${{secrets.SSH_PRIVATE_KEY}}
          command: |
            cd ${{secrets.REMOTE_PATH}}
            sudo -u www-data git pull
            sudo supervisorctl restart ${{secrets.SUPERVISOR_PROG_NAME}}
