name: Build and Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Python 3.7.5
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7.5
      
      - name: Install requirements
        run: pip install -r requirements.txt
      
      - name: Linting
        run: |
          pip install flake8
          flake8
    
      - name: Deploy using SSH
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ${{secrets.DEPLOY_SCRIPT_PATH}}
          username: ${{secrets.SSH_USERNAME}}
          privateKey: ${{secrets.SSH_PRIVATE_KEY}}
          host: ${{secrets.SSH_HOST}}
          port: ${{secrets.SSH_PORT}}
