name: Test and Deploy

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Python 3.7.5
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7.5

      - name: Install requirements, flake8, and pytest
        run: |
          pip install -r requirements.txt
          pip install flake8
          pip install pytest
      
      - name: Linting
        run: pip install flake8
      
      - name: Testing
        run: python -m pytest
        
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Deploy using SSH
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ${{secrets.DEPLOY_SCRIPT_PATH}}
          username: ${{secrets.SSH_USERNAME}}
          privateKey: ${{secrets.SSH_PRIVATE_KEY}}
          host: ${{secrets.SSH_HOST}}
          port: ${{secrets.SSH_PORT}}
